travis:
  secure:
    BINSTAR_TOKEN: nnx4FknJ71sGcq1lnoUHu49MLQLH5w/n0j6zr6dTUlmdCSn/nAT/qdJhhiB4Wm2PgW/E+rtcfwcZWzolywpZ5wo62h+BWTM5y8wctq68BcqHp+zU28BtHtEu2GGvaLpPzw3mpfQlIzjEs6ryX17WFgatgrlfApXkOKjU5xuONoWIFDnr0106rEisrcNrPn5/m3gdRJFWSNw25DxHrlwnGem6z6Wb+UXyzv4LZw1OSS3rwoGyoNnHbIIDEJnrhnMmwrDh/obuktGCz0B2u3VYAz700CutWo9R+WjDSwZX9XoAj30BhcxTQ6LTePKnTPNnOI/jYJEBn2fa7NDJ2oFA5iQWUXXt/fmXofQzVK/lkGu3qkYr+k00yiyIVaKGeMLRWtHMgN0p0Vbex2/TMFSgPcIHUS8+Byjfk7enfDuic+AWPjL2M+T1XslFW4vWtDah8qpvv0iksYFOWiQmOl2o8Ci7hSI02gLPWsLBLcaXiPF5Opm/GjGhqrPCpei+mSotVdZI7qA1bzBoEDECrNIDGcapjzP+BPeslNcQTPYKN6Iaf6uIH244sH6wZBbnOuXcHJxyb6Mv/0fND9A3+PI+ruDa/gn6MjlziFnwCmyMyT5jylSaRaYY+ZPSOlsquCqAzcTac++GuG2R6LlMVIwPik2WStb6eLTj7VX+W4t9dxo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
