travis:
  secure:
    BINSTAR_TOKEN: G4siKoAkCdiUpB650ig9BVnecMRnbxVmso8blLwM6aAVGQHuD1FSJsxH1HML4m6EHqIccbOLbAdUT9vpMmq1jBhxzS5tBTOQNDPJStnLQjUosrjUlj0aRbIWd+ZvDQuW9h5NFfIb3mqcBYNZStftE4NUaPo2IJHi/+53htegoQmbTwlrBGaSNFlLMT2bsEkti5EmjFSikMuVHsWZ1/JZx+H2RJepVSF46Skjj9xPfKZe30/iRBUwmnH7pGIYtNZXHLXkAwWWwxu6Lo8bZeKj53wM1ntjAhT6PR4fA3/32bWIUWzD5kZqan1reShspMjM3IgHYQCfuORxCGRY7mAUzUnyxVhL92+f7WNnZkDmYLywoS49Q6gx+H5roVsZ3/JnUxQ7Zq6aTvKQdNSIcAWSSPe0UoKjrrfPSwWymv9N+1NX+rdyLEaoa4r0IIBfQW70s52KTKqOAHk0MTdFl9soudY3EszLleicqB1jOW8K06jCOPxWIyfP/ChtF/Dg/eFPSeb1FW1S8XLysIbE8aiiXZ5jERuZyFPdJKjaE6lIGqD7UfsK8lI0US7VUc1ADfh1pxxUUW7TzKDiuy4IrBtdjZ6pBZg84qrvDcSff2vCJBehaC7erAp/HULQCIN5I1JdzAfhy0iqutObylXKTPk356zmfJB+ecOZ2Eg3WxHnUcM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
